name: build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: 67b2e434-10b3-4187-b97d-0ec8d7b59d80

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - run: bash <(curl -s https://codecov.io/bash)

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12
      - run: yarn
      - run: yarn build
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.2.0
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: ".*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.QMBOT_NPM_TOKEN }}
